= Reading List for Jul 2019
Zed Tan <zed@shootbird.work>
:toc: auto
:sectlinks:
:sectnums:
:source-highlighter: pygments
:assetdir: /jul2019-assets

== Transhumanism

https://www.wired.com/story/this-robot-fish-powers-itself-with-fake-blood

- scientists found toyed with the idea of fake fats for energy storage.
- fake blood (circulatory media to store and distribute energy) instead.
- created artificial lionfish with fake blood.
- Robert Shepherd: “In our fluid, we're transmitting force and we're transmitting electrical power.”
- > Thus the fluid energizes the fish. But it also acts as a traditional hydraulic fluid, in that it transmits force in the tail and pectoral fins. When the pumps push the fluid to the fins, they bend back and forth to propel the robot. The pectoral fins work in the same way to steer the fish left and right.
- Robert Katzschmann, whose team built a Lithium ion robot fish: “The power density is about 30 to 150 times less in what they're showing compared to what a lithium ion battery can do,”
