= Reading List for Feb 2019
Zed Tan <zed@shootbird.work>
:toc: auto
:sectlinks:
:sectnums:
:source-highlighter: pygments
:assetdir: /feb2019-assets

== Security

=== Device recovery via hacking

Ken Westin, "DEF CON 23: Confessions of a Professional Cyber Stalker – Ken Westin",
published 18 Sep 2015 on YouTube.
Available: https://www.youtube.com/watch?v=zVJGY2bZ-Ko&feature=youtu.be

(snippets taken from youtube transcripts; so they may not be 100% grammar checked or accurate)

Takeaways:

* Ken Weston specializes in device recovery.
* Has been writing tracking software, even before "Find my device" functionality by Apple and Google's services.
* Software ethics:
+
[quote, Black Hat Review Board]
____
"I think you should reflect on the ethical implications of the technology that you're happily distributing."
____
* Intent was to write secure tracking software that can be used ethically:
+
[quote]
____
\[...] you can
probably imagine some of the work I do
has its critics — it's usually from folks
who don't understand the intentions or
the background of the tools. The fact is
there are incredibly there tools that
are much more invasive that are
available to do more nefarious things
such as rats a lot of malware out there
that people can use if they actually
want to spy on someone you know.
____
* Most tracking software are intrusive and dangerous to the user:
+
[quote]
____
Actually investigating some of the other
theft recovery tools that were out there,
I found a lot of them actually had
backdoors into the systems. They would
actually gather more data than they
really needed, and so I tried to develop
a tool that was both useful for law
enforcement investigations but also
balance the privacy implications as well.
____
* Autorun is evil.
* Rando USB devices are bad.
* IP addresses are bad for pinning activity to identity:
+
[quote]
____
So one thing I learned is
that the trouble with getting the IP
address \[...] you know it's very very difficult to use
for attribution. One thing I found is
that law enforcement doesn't like
paperwork. So when you're dealing
with IP addresses, they have to do a lot
of filing: they have to go through to get
a court order to get that information
from an ISP, and you know some of this
processes can take anywhere from two weeks
to three months.
____

== AI/ML

=== Deepmind Starcraft AI cheats

Rob Beschizza, "Looks like the Deepmind Starcraft AI relied on superhuman speed after all", published 27 Jan 2019 on _boingboing_.
Avail: https://boingboing.net/2019/01/27/looks-like-the-deepmind-starcr.html

Rob reports that Deepmind was found by Aleksi Pietikäinen, a psych student, who made the case that AlphaStar won
Starcraft 2 players because of "its inability to unlearn the human players’ tendency to spam click."
footnote:[https://blog.usejournal.com/an-analysis-on-how-deepminds-starcraft-2-ai-s-superhuman-speed-could-be-a-band-aid-fix-for-the-1702fb8344d6]

One of the things that Aleksi points out is that DeepMind's way of measuring play speed is by comparing APM (actions per minute),
while there's another measure that they should have used, which is EPM (effective APM).
The DeepMind paper link:https://deepmind.com/blog/alphastar-mastering-real-time-strategy-game-starcraft-ii/[claims]
that the mean APM of AlphaStar being significantly lower than human players
— 280, compared to 390 and 678 recorded by the human players it played against.
But Aleksi notes that if we were to convert this to EPM, AlphaStar's EPM would effectively be 100% of the clicks it makes,
while it would be a fraction of the humans' APM.

The second thing that Aleksi points out about this is that the metrics recorded by DeepMind
don't take into account how long each player (human and non-human) can sustain high APM rates.
Aleksi notes that AlphaStar appears to be able to sustain an APM of 1500 over 5 seconds —
while a human would be hard pressed to sustain an APM of 500.

There's lots of other stuff that I won't get into here, such as how when APM spikes occur,
and the role of spam clicking which artificially inflates APM for human players.
But we can see here how DeepMind makes certain mistakes in their claims that
boil down to:

. Misreading the relation between human behaviour and human psychology, and
. Assuming that it is possible to make hardware behave like wetware.

=== Google publishes whitepaper on AI governance

Tom Simonite, "GOOGLE SAYS IT WANTS RULES FOR THE USE OF AI—KINDA, SORTA", published 2 Feb 2019 on _Wired: Business_.
Avail: https://www.wired.com/story/google-says-wants-rules-ai-kinda-sorta

[quote]
____
Google’s paper is much broader in scope than Microsoft’s proposals on facial recognition, and considers more AI uses and concerns. It’s also more cautious, and doesn’t strongly advocate for specific new regulations. The search company champions self-regulation, highlighting how it has chosen not to offer a general-purpose facial recognition service—as Microsoft and Amazon do—due to concerns it could be used to “carry out extreme surveillance.” The paper also says Google has limited some of the AI research code it has released, to reduce the risk of misuse.
____

The writer ostensibly wants to cast doubt on Google's attempt to be a good citizen in the
AI biosphere, but I think it's always prudent to be cautious about recommending
or acceding to new regulation. What most overlook when talking about regulation is
that it is inherently violent, rigid, and unsympathetic by design.

To read: the whitepaper itself, which can be found here: 
https://www.blog.google/outreach-initiatives/public-policy/engaging-policy-stakeholders-issues-ai-governance/
(link:{assetdir}/perspectives-on-issues-in-ai-governance.pdf[pdf])

=== Amazon's face recognition tech is still flawed and still being used by law enforcement

Bryan Menegus, "Defense of Amazon's Face Recognition Tool Undermined by Its Only Known Police Client",
published 31 Jan 2019 on _Gizmodo_.
Avail: https://gizmodo.com/defense-of-amazons-face-recognition-tool-undermined-by-1832238149

[quote]
____
Faced with two independent studies that found its facial recognition software returns inaccurate or biased results, Amazon has repeatedly claimed that the researchers failed to use the software, called Rekognition, in the way the company has instructed police to use it.

However, the only law enforcement agency Amazon has acknowledged as a client says it also does not use Rekognition in the way Amazon claims it recommends, Gizmodo has learned. In doing so, the law enforcement agency undermines the very argument Amazon uses to discredit critical research about Rekognition.

\[...]

Amazon’s documentation states that law enforcement clients may “use a similarity threshold lower than 99% for scenarios that benefit from a larger set of potential matches [such as] finding missing persons,” but according to a source with knowledge of the WCSO’s Rekognition setup and usage who asked to remain anonymous for fear of retribution, the software is deployed in cases ranging from theft to homicide.
____

Documenting an allowed use-case, and building such important restrictions into your application,
and _then_ blaming your customer when your software is not used as per spec is a _design cop-out_
and irresponsible. It's like saying you've designed a car that only works if you're stepping on the
gas pedal at a specific angle of 62–69º.

=== China: Face anti-graft face-recognition too efficient?

Stephen Chen, "Is China’s corruption-busting AI system ‘Zero Trust’ being turned off for being too efficient?",
published 4 Feb 2019 on _South China Morning Post_.
Avail: https://www.scmp.com/news/china/science/article/2184857/chinas-corruption-busting-ai-system-zero-trust-being-turned-being

Takeaways:

* Anti-graft AI system dubbed "Zero trust".
* Resistance by gov officials to wide-reaching anti-graft "data experiment".
* Extensive tracking of government employees:
+
[quote]
____
Beijing has been developing a nationwide facial recognition system using surveillance cameras capable of identifying any person, anywhere, around the clock within seconds. In Guizhou, a cloud system tracks the movements of every policeman with a live status report.
____
* Participation by private contractors:
+
[quote]
____
Major Chinese telecommunication companies such as ZTE have won government contracts to develop blockchain technology to prevent the modification of government data by unauthorised people or organisations.
____
+
[quote]
____
Jointly developed and deployed by the Chinese Academy of Sciences and the Chinese Communist Party’s internal control institutions to monitor, evaluate or intervene in the work and personal life of public servants, the system can access more than 150 protected databases in central and local governments for cross-reference.
____
* Still a black box — zero explainability:
+
[quote]
____
“AI may quickly point out a corrupt official, but it is not very good at explaining the process it has gone through to reach such a conclusion,” the researcher said. “Although it gets it right in most cases, you need a human to work closely with it.”
____
* *Presumption of guilt* upon identification by the system:
+
[quote]
____
Once its suspicions have been raised it will calculate the chances of the action being corrupt. If the result exceeds a set marker, the authorities are alerted.

A computer scientist involved in the programme who asked not to be named said that at that stage a superior could then contact the person under scrutiny and perhaps help him avoid “going down the road of no return with further, bigger mistakes”.
____
* Some regions have chosen to shut the "experiment" down:
+
[quote]
____
Still, some governments – including Mayang county, Huaihua city and Li county in Hunan – have decommissioned the machine, according to the researchers, one of whom said they “may not feel quite comfortable with the new technology”.
____
* Again, presumption of guilt, but at the same time admits that human interference and verification is required (lip service?):
+
[quote]
____
“It is not easy … we are under enormous pressure,” he said, insisting that the main purpose of the programme was not to punish officials but to “save them” at an “early stage of corruption”.

“We just use the machine’s result as reference,” Zhang said. “We need to check and verify its validity. The machine cannot pick up the phone and call the person with a problem. The final decision is always made by humans.”
____
* Government officials reluctant to cooperate with programme, either evidence of guilt or they know how this info can be easily used against them:
+
[quote]
____
A party disciplinary official in Xiushui county, Jiangxi, who took part in the Zero Trust project said no government officials were willing to provide the necessary data.

“But they usually comply with a bit of pressure,” said the official, who asked not to be named because of the sensitivity of the technology.
____
* No official sanction or decree to use the system:
+
[quote]
____
The system is still running in Xiushui, but its fate is uncertain. Some officials have questioned the machine’s right to access a sensitive database because there is neither a law nor regulation authorising a computer or robot to do so.
____
* Aside:
+
[quote]
____
Last month, a court in Shanghai became the first ever in China to use an AI assistant at a public hearing, Xinhua reported.

The machine, code-named “206”, has the ability to record conversations, show evidence such as surveillance camera footage when mentioned by lawyers, and compare testimonies to help judges spot discrepancies, the report said.
____

== General Tech

== Elasticsearch

- Hugo + Elasticsearch utility: https://github.com/clarketm/hugo-elasticsearch

=== WebRTC

ICE footnote:[Interactive Connectivity Establishment] is a protocol
that relies on STUN footnote:[Session Traversal Utilities for NAT
footnote:[Network Address Translation; how networks manage a single public IP address across several devices in an internal network]]
and TURN footnote:[Traversal Using Relay NAT] servers to
perform magic that finds out which devices want to communicate with each other.

TURN servers can also host STUN services.
You can deploy one physical server that hosts TURN and STUN services.

STUN allows webrtc services to find your public IP address.
TURN relays the media/data to be transmitted.

Resource: https://bloggeek.me/webrtc-basics-1-missing-servers/

Plain language take (?):

- ICE: WebRTC connectivity protocol
- TURN: Media relay server
- STUN: Device name resolution server

Aside: The acronyms don't make sense and are difficult to remember.
Plus the acronyms picked are not neutral i.e. carries baggage from
their literal meanings. Would have been better to use abbreviations
which are usually neutral e.g. NAT.
ICE connotes stasis and is also the name of the US Immigrations and Customs Enforcement agency.
TURN makes the most sense. STUN also indicates statis and doesn't
bring to mind dynamic name resolution.

When you hear ICE described as a server, they might be referring to
a single STUN and TURN server. See https://github.com/pion/webrtc/rtciceserver.go

Google appears to have a public STUN server available here: `stun.l.google.com:19302` footnote:[https://github.com/pion/webrtc/examples/save-to-disk]

== Journalism

=== Pressers in Germany are held by the press

Christoph Droesser, "In Germany, the press hosts the press briefings", published 29 Jan 2019 in _Columbia Journalism Review_.
Avail: https://www.cjr.org/analysis/germany-press-briefings.php
(link:{assetdir}/germany-pressers.pdf[pdf])

[quote]
____
Journalists as the hosts, not the guests, of press briefings is a long-held tradition in Germany. It was exactly a hundred years ago, after Germany lost World War I, that the Berlin correspondents of the major newspapers decided they didn’t want to keep depending on misleading government communiqués that the emperor had provided during the war. Those were revolutionary times, and this revolution was one of the few that stuck. Until 1933, when Hitler’s minister of propaganda, Joseph Goebbels, liquidated the so-called Reichspressekonferenz.

But after World War II, on the day that West Germany’s parliament elected the first chancellor, Konrad Adenauer, a group of journalists got together and founded a new organization, the BPK. Adenauer was their first guest, and today no leading politician can afford not to expose themselves to the unfiltered and sometimes irreverent questioning of the press corps at least a couple of times a year. “The public image of a politician depends at least in part on whether they are prepared to confront our questions,” says Gregor Mayntz.
____

=== Seattle Times is incentivizing reporters to grow subscriptions

Max Willens, "How the Seattle Times is empowering reporters to drive subscriber growth", published 31 Jan 2019 in _Digiday UK_.
Avail: https://digiday.com/media/seattle-times-empowering-reporters-drive-subscriber-growth/

In the aftermath of the "pivot to video"
link:https://slate.com/technology/2018/10/facebook-online-video-pivot-metrics-false.html[fallout],
and newsrooms at link:https://www.nytimes.com/2019/01/23/business/media/buzzfeed-layoffs.html[Buzzfeed]
and link:https://variety.com/2019/digital/news/vice-media-layoffs-250-employees-1203125890/[Vice]
reporting massive layoffs,
a glimmer of hope comes from the Seattle Times which
says its digital subscriptions grew by 38 percent because it changed its metrics from clicks to subscriptions.

It's also reassuring to know that the old wisdom still holds true:
KPIs are terrible because they can be easily gamed —
focusing instead on long term and sustainable gains is the better business strategy.

[quote]
____
Over the past year, the news publisher, which grew its digital subscriber base 38 percent to 40,000 in 2018, has been trying to get small teams of reporters to think more entrepreneurially about driving subscriptions. It wants them to not just monitor which kinds of content visitors read on their way to paying but also to experiment with new content and packaging formats designed to keep readers engaged.

In 2017, the Times gave its newsroom staff access to a dashboard that showed reporters which stories they published were driving subscriptions. Next, the Times’ executive editor, Don Shelton, formed several teams, called mini-publishers, which paired editorial staffers with members of the paper’s digital audience, product and business intelligence teams to figure out what kinds of content the audience likes, how to make more of it, and so on. The first two teams, which focused on local politics and the University of Washington’s football team, launched in 2017. But in 2018, it expanded that effort to more topics the Times knows are big subscription drivers, including the Seattle Seahawks and Mariners, opinion, real estate, outdoor and travel, and local food and drink.

\[...]

In other cases, the data helped teams adapt their coverage strategies. A team of reporters working on a large series about orca whales in the Puget Sound started publishing more quick-hit, breaking news pieces because they noticed immense audience interest in the topic, Gawlowski said.

The Times does not have a hard number of subscriptions it can attribute to these efforts. But Gawlowski sees the change in culture and thinking as a key element in subscriber growth, though one that’s hard to separate from the efforts of the publisher’s business teams. “The performance of our stories is increasing, but it’s a group effort between the newsroom and and the business side,” he said.

\[...]

“You need to think about things where the readers have given you a clear signal that they like it,” said Gren Manuel, a London-based media and publishing consultant. “I still just see so many stories where I ask, ‘Who was this written for?’”
____

== Game studies

=== General Resources

Quick survey/collection of resources I've collected on Game Studies over the years.

* MIT Press's titles on game studies: https://mitpress.mit.edu/topics/game-studies
* 

My stuff:

* Guest lecture I gave on documentaries, games + narratives: https://www.zeddee.com/pdfs/CS4026-Documentaries-Games-and-Narratives.pdf
* My one and only published piece on games: https://killscreen.com/articles/what-time-got-wrong-about-last-us/
* Brief essay on navigational space in games: https://www.zeddee.com/posts/why-i-play-the-binding-of-isaac/
* My transcription of Ian Bogost's Wired talk "A Game Designer Explains the Counterintuitive Secret to Fun": https://www.zeddee.com/posts/ian-bogost-on-the-design-of-fun/

=== Cheating in games

* https://www.techradar.com/news/gaming/cheating-in-games-the-good-the-bad-and-the-entirely-necessary-653045
* https://feross.org/cheating-in-video-games/
* https://mindtheethos.com/2016/08/14/the-psychology-of-cheating-why-do-people-cheat-in-multiplayer-games/
* Mia Consalvo, author of the book Cheating: Gaining Advantage in Videogames

Value judgement of cheating is not straightforward in video games, because:

* One can say that cheating would be contravening the rules of play.
* But in video games, it is possible to interpret "rules of play" as
what is literally written as code in the game.
That is, rules of play are literally codified as code/engine in the game.
* This is sometimes referred to as the game "engine",
and playing in predefined situations and computer-generated opponents
is commonly referred to as "PvE" or "Player versus Engine" type of gameplay.
* But this disregards the social layer that sits on top of the game engine,
which has its own rules.
* Another layer of complexity is whether the player is engaging in the game "as is",
i.e. as the game designers intended, or is the game itself the game as a programmatic entity
meant to be tweaked, hacked, etc. Good example of these games are the CTFs common in
programming communities.
** Also, this sort of "cheating" is used prevalently in meta-games, e.g. %any speedruns and their variants.
* But the deeper we delve into this, the more we can see that the further we get into
how the definition of cheating is malleable enough to get around any technical constraint,
the more we can see that the social layer is important in defining the shape of cheating.


== Mediated Spaces

=== Context collapse

https://www.theatlantic.com/international/archive/2015/04/the-abuse-of-satire/390312/

fail state of "clever" is "asshole".

== Wierd

=== Biology of Baboushka Dolls

https://worldbuilding.stackexchange.com/questions/138133/russian-dolls-how-do-they-reproduce

[quote, OP "chasly from UK"]
____
I believe that Russian Dolls reproduce asexually. They are born pregnant. At the time of birth, the outer doll dies. What is now the outer doll grows until it reaches full size at which point it gives birth and dies. The birth process is simple - the outer doll simply splits in half around its middle. A new inner doll forms at the same time.
____

p.s.w.g. points out that the Volvox, a type of freshwater algae, reproduces just as OP describes:

[quote, wikipedia, https://en.wikipedia.org/wiki/Volvox]
____
Individual volvox cells, a kind of freshwater algae, reproduce in the conventional way (more or less), however, they also collect into spherical colonies (called volvocates, I think) with a tiny opening at one end. These spheres can reproduce by internal budding, with immature spheres growing within the body of the 'mother' sphere. Then at some point, the mother turns itself inside-out by inverting itself through the opening, releasing the 'daughter' spheres into the wild. The point where the daughter sphere connected with this interior of the mother becomes the opening of the daughter sphere (sort of like a navel in mammals). The cells that formerly composed the mother sphere don't simply die, however. Most of them are absorbed by one of the daughter spheres.
____

== Links

=== Managing people

Objectives and Key Results (OKRs), an alternative to KPIs:

* https://rework.withgoogle.com/guides/set-goals-with-okrs/steps/introduction/
* https://rework.withgoogle.com/guides/set-goals-with-okrs/steps/avoid-OKR-writing-mistakes/

=== Learning stuff

- Academic torrents: http://academictorrents.com/

=== Cryptography

- Stenography tools: https://0xrick.github.io/lists/stego/

=== Design

- Great posters from gov.uk on various public service things: https://github.com/alphagov/govdesign.git

== Glossary

=== Machine Learning/AI

==== Neuromorphic engineering

[quote, https://en.wikipedia.org/wiki/Neuromorphic_engineering]
____
Neuromorphic engineering, also known as neuromorphic computing,[1][2][3] is a concept developed by Carver Mead,[4] in the late 1980s, describing the use of very-large-scale integration (VLSI) systems containing electronic analog circuits to mimic neuro-biological architectures present in the nervous system.[5] In recent times, the term neuromorphic has been used to describe analog, digital, mixed-mode analog/digital VLSI, and software systems that implement models of neural systems (for perception, motor control, or multisensory integration). The implementation of neuromorphic computing on the hardware level can be realized by oxide-based memristors,[6], spintronic memories,[7] threshold switches, and transistors.[8]
____
