= Reading List for Sep 2019
Zed Tan <zed@shootbird.work>
:toc: auto
:toclevels: 3
:sectlinks:
:sectnums:
:source-highlighter: pygments
:assetdir: /sep2019-assets

== Human things

=== The Missing Body of the Machine

Ben Medlock, "The body is the missing link for truly intelligent machines",
published 21 Aug 2019 on _Sinapticas_.
Available: https://sinapticas.com/2019/08/21/the-body-is-the-missing-link-for-truly-intelligent-machines

[quote]
____
I understand the appeal of this view, because I co-founded SwiftKey,
a predictive-language software company that was bought by Microsoft.
Our goal is to emulate the remarkable processes by which
human beings can understand and manipulate language.
We’ve made some decent progress: I was pretty proud of the
elegant new communication system we built for the physicist
Stephen Hawking between 2012 and 2014. But despite encouraging results,
most of the time I’m reminded that we’re nowhere near achieving human-like AI.
Why? Because the layered model of cognition is wrong.
Most AI researchers are currently missing a central piece of the puzzle: embodiment.
____

* This is a thought that's been put forward constantly by Hubert Dreyfus,
who argued that embodiment is necessary for a human understanding of the world.
* It's also a train of thought that uses as a premise that human intelligence is the de facto goal of machine intelligence.
* Once you remove that premise, you free up the possiblity of machines that are
intelligent by a different metric than humans are intelligent.
* E.g. humans will never be able to compete with a machine within the bounds of a closed and known system
e.g. Go, Dota 2 etc.
* A useful analogue would be how we consider and measure animal intelligence by basically
imposing a set of human standards e.g. a dog is intelligent if it can be trained to accomplish a series of tasks
* It's been shown that animal intelligence exceeds those bounds once we think past
this imposition of human standards, e.g. a dog is intelligent if it displays self-directedness instead of submitting
itself to a human imposed goal, like breaking out of a cage to get to a bag of food on a shelf, rather than knowing
how to roll over and play dead.
* (I also think that animal training is an inherently colonial and unethical impulse, but that's another story altogether)

[quote]
____
This means that when a human approaches a new problem, most of the hard work has already been done.
In ways that we’re only just beginning to understand, our body and brain,
from the cellular level upwards, have already built a model of the world
that we can apply almost instantly to a wide array of challenges.
But for an AI algorithm, the process begins from scratch each time.
There is an active and important line of research, known as ‘inductive transfer’,
focused on using prior machine-learned knowledge to inform new solutions.
However, as things stand, it’s questionable whether this approach will be
able to capture anything like the richness of our own bodily models.
____


=== The Human Log

In a related article or tweet that I cannot remember the source for (will update when I do),
someone described journaling as a "diagnostic socket" for the human brain,
a metaphor that I am quite partial to given how much I'm accused of being
very much like a machine (and how much I prefer interacting with them rather than humans).

In a similar vein,
link:neilkakkar.com[Neil Kakkar]
writes a longer post about how humans also,
like computers and other systems, need a log:
https://neilkakkar.com/the-human-log.html

I enjoy in particular his opening grafs on the nautical origins of the term "log"
(I am quite fond of ships and the sea):

[quote]
____
The log is an interesting invention. It began with 16th century ships – surrounded with water, no land in sight, no sense of direction, and no sense of speed. What did you have to compare your speed with anyway?

The sailors were ingenious. They used a log - a real piece of wood - attached to a string. They’d throw it in the water and use it to measure speed1. Then they’d track this speed over time, in a logbook.

That’s the origin story of log books, now known as logs.

Over time, the logs grew to track even more information. The sailors felt that tracking their speed wasn’t enough. They filled gaps in their measurements - the weather, incidents, and the last time someone cleaned the toilet.

The idea? If you have a log, you can figure out what went wrong. You can figure out where you made mistakes. If the ship crashes, you know the last state it was in, thanks to the logs.
____

Other noteworthy points:

* "[...] logs serve two main purposes. (1) Crash resolution and (2) Behaviour detection."
* "Every important system has logs since they’re necessary to improve the system over time."
* Human logs as  means to detect "micro-crashes", and derive diagnostic value from them.
* Micro-crashes are things like headaches, sleep-irritation i.e. minor ailments that may signal deeper issues.
* Nakkar suggests quite a list of things that should go into a human log …
which forms what I can see is a useful baseline but
seems a bit too mechanical for my own taste
(plus that's a lot of work) e.g. daily weight, _bowel movements_ etc.
* Data-driven journaling.

On a separate note, a todo app that I've been using since 2014 has stopped syncing on iCloud,
so I really need to figure out a better way to sync all my thoughts
the links that I collect on a daily basis. May need to actually build my own.

== Disinformation

=== Ignorance and Stupidity as apparatus of governance

Source: danah boyd, founder and president at Data & Society. "Agnotology and Epistemological Fragmentation", talk given at  the Digital Public Library of America conference (DPLAfest) on 17 apr 2019. https://points.datasociety.net/agnotology-and-epistemological-fragmentation-56aa3c509c6b

As I work through this article, I am thinking of Bernard Stiegler's
_States of Shock: Stupidity and Knowledge in the 21st Century_ (Cambridge: Polity Press, 2015),
where he writes about the _immaturity_ (in the sense of "not reaching maturity", as in "age of maturity")
of the voting populace. He specifically selects the term "_bêtise_" to describe
this behaviour, demonstrated and perpetuated by institutions in particular.

Going to be quoting lots of snippets from danah boyd's talk because it's
dense and full of important stuff.

On "agnotology":

[quote]
____
Epistemology is the term that describes how we know what we know.
Most people who think about knowledge think about the processes of obtaining it.
Ignorance is often assumed to be not-yet-knowledgeable.
But what if ignorance is strategically manufactured?
What if the tools of knowledge production are perverted to enable ignorance?
In 1995, Robert Proctor and Iain Boal coined the term “agnotology”
to describe the strategic and purposeful production of ignorance.
In an edited volume called Agnotology, Proctor and Londa Schiebinger
collect essays detailing how agnotology is achieved.
Whether we’re talking about the erasure of history or the undoing of scientific knowledge,
agnotology is a tool of oppression by the powerful.
____

This one is a punch in the gut because it's so true:

[quote]
____
Many people who are steeped in history and committed to evidence-based decision-making are experiencing a collective sense of being gaslit […]
How do you process a black conservative commentator testifying before the
House that the Southern strategy never happened and that white nationalism
is an invention of the Democrats to “scare black people”?
Keep in mind that this commentator was intentionally
trolled by the terrorist in Christchurch;
she responded to this atrocity with tweets containing “LOL” and “HAHA.”
____

More:

[quote]
____
**This terrorist understood the vulnerabilities of both social media and news media.**
The message he posted on 8chan announcing his intention included links to his manifesto and other sites,
but it did not include a direct link to Facebook;
he didn’t want Facebook to know that the traffic came from 8chan.
The video included many minutes of him driving around,
presumably to build audience but also, quite likely,
**in an effort to evade any content moderators that might be looking**.
He titled his manifesto with a well-known white nationalist call sign,
knowing that the news media would cover the name of the manifesto,
which in turn, would prompt people to search for that concept.
And when they did, they’d find a treasure trove of anti-Semitic and white nationalist propaganda.
**This is the exploitation of what’s called a “data void.”**
He also trolled numerous people in his manifesto,
knowing full well that the media would shine a spotlight on
them and create distractions and retractions and more news cycles.
**He produced a media spectacle.**
And he learned how to do it by exploiting the information ecosystem we’re currently in.
Afterwards, every social platform was inundated with millions
and millions of copies and alterations of the video uploaded
through a range of fake accounts, either to burn the resources
of technology companies, shame them, or test their guardrails for future exploits.
____

This:

[quote]
____
What’s at stake right now is not simply about hate speech vs. free speech
or the role of state-sponsored bots in political activity.
It’s much more basic.
**It’s about purposefully and intentionally seeding doubt to fragment society.**
To fragment epistemologies. This is a tactic that was well-honed by propagandists.
____

The problem:

[quote]
____
Herein lies the problem.
One of the best ways to seed agnotology is to make sure that doubtful
and conspiratorial content is easier to reach than scientific material
____

Tactics used to seed ignorance/epistemological fragmentation:

* Exploiting 'data voids' like the Christchurch shooter did, illustrated above.
* Co-opting and re-purposing existing terms, twisting their meaning to communicate a spurious idea.
* (To boyd, this is seems the most important) Producing terms that are
"**strategically created to achieve epistemological fragmentation**".
+
[quote]
____
In the 1990s, Frank Luntz was the king of doing this with terms 
like partial-birth abortion, climate change, and death tax. Every 
week, he coordinated congressional staffers and told them to 
focus on the term of the week and push it through the news media. 
All to create a drumbeat.
____

This strategic manufacture of terms entails:

* A shifting of objectives.
Instead of focusing on gaining media attention,
the goal instead is to "create a world of content
and then to push the term through to the news media".
* By twisting an existing term or inventing one,
or simply selecting a term that is not known to
the general public, they exploit a data void that
funnels internet traffic to these prepared content pots
where they are free to further undermine
the ability for actual facts to appear reliable.
* "**Media manipulators are also very good at messing with structure. **"
+
[quote]
____
YouTube has great scientific videos about the value of vaccination, but countless anti-vaxxers have systematically trained YouTube to make sure that people who watch the Center for Disease Control and Prevention’s videos also watch videos asking questions about vaccinations or videos of parents who are talking emotionally about what they believe to be the result of vaccination. They comment on both of these videos, they watch them together, they link them together. This is the structural manipulation of media.
____

This one is particularly painful:

[quote]
____
Journalists often get caught up in telling “both sides,” but the creation of sides is a political project.
____

Kicker (emphasis mine):

[quote]
____
You will not achieve an informed public simply by making sure that high quality content is publicly available and presuming that credibility is enough while you wait for people to come find it. You have to understand the networked nature of the information war we’re in, actively be there when people are looking, and **blanket the information ecosystem with the information people need to make informed decisions.**
____

=== Agnotology in China

This is a continuation of the previous section: 
link:#_ignorance_and_stupidity_as_apparatus_of_governance[Ignorance and Stupidity as apparatus of governance]

I'm just noting that the approach we have to take when attempting
to apply similar ideas of disinformation to China has to
very carefully consider the vastly different
information climates that pervade China internally,
and the information posture that they project externally.

For instance, the baseline posture for news media in China is
assumed to be propagandist/disinformation by default,
even by their own populace. This has led to a shadow
information economy (and even so, one that is not very in
the shadows but sort of sanctioned by the state through
it being allowed to exist as part of the massive
social credit/ewallet system).

Epistemological fragmentation then can be said to be
actually part of the state apparatus, being used explicitly
to subjugate and to assimilate public thought into the party
agenda. This was a strategy already in use during the Maoist Cultural Revolution. 

=== Misconceptions about disinformation leaves us vulnerable to manipulation

Kate Starbird, "Disinformation’s spread: bots, trolls and all of us", published 24 July 2019 on _nature_.
Available: https://www.nature.com/articles/d41586-019-02235-x link:{assetDir}/d41586-019-02235-x.pdf[[pdf\]]

* "[…] disinformation is not as cut-and-dried as most people assume:
those behind disinformation campaigns purposely entangle orchestrated action with organic activity."
* "When my lab studied the online activism around #BlackLivesMatter, the conspiracy theories that crop up after crises, and the Syrian conflict, we uncovered disinformation campaigns promoting multiple, often conflicting, views."

[quote]
____
Perhaps the most common misconception is that disinformation is simply false information.
If it were, platforms could simply add ‘true’ and ‘false’ labels,
a tactic that has often been suggested.
But disinformation often layers true information with false —
an accurate fact set in misleading context,
a real photograph purposely mislabelled.
The key is not to determine the truth of a specific post or tweet,
but to understand how it fits into a larger disinformation campaign.

Another misconception is that disinformation stems mainly from agents
producing false content (paid ‘trolls’) and automated accounts (‘bots’)
that promote it.
But effective disinformation campaigns involve diverse participants;
they might even include a majority of ‘unwitting agents’
who are unaware of their role,
but who amplify and embellish messages that polarize communities
and sow doubt about science, mainstream journalism and Western governments.
____

* disinformation is not just false information.
* disinformation usually layers true information with false, with the goal of
link:#ignorance-and-stupidity-as-apparatus-of-governance[epistemological fragmentation].
* disinformation does not necessarily propogate through bots or agents/paid 'trolls'
* effective disinformation campaigns involve diverse participants, including 'unwitting agents',
creating a dessimination vector that is difficult to categorize and identify as a result
of a campaign.

Some of this is new to me:

[quote]
____
This strategy goes back decades.
It was laid out most explicitly by Lawrence Martin-Bittman,
who defected from Czechoslovakia to the West in 1968 and
became a prominent academic (L. Bittman The KGB and Soviet Disinformation; 1985).
Historically, manipulating journalists was a primary strategy.
Now, social-media platforms have given voice to new influencers
and expanded the range of targets.
We see authentic members of online communities become active
contributors in disinformation campaigns,
co-creating frames and narratives.
One-way messages from deliberate actors would be relatively easy to identify and defuse.
Recognizing the role of unwitting crowds is a
persistent challenge for researchers and platform designers. So is deciding how to respond.
____

== Philosophy

=== Desire without lack

https://ndpr.nd.edu/news/malebranche-theological-figure-being-2/

Reviewed by Ed Pluth, California State University, Chico.
Alain Badiou, Malebranche: Theological Figure, Being 2,
Jason E. Smith and Susan Spitzer (trs.), Columbia University Press, 2019, 193pp., ISBN 9780231174787.

Not really interested in Badiou, but I found this snippet particularly interesting:

[quote]
____
Consistent with not having a doctrine of the event, Malebranche also has to puzzle out a way in which God can desire, but still not lack.

> Malebranche's big problem will be how to think desire without lack. Glory, as we shall see, is ultimately a category of God's desire: what God desires is his own glory. This goes without saying, because if he didn't desire it, he wouldn't make anything, and especially not the world. (85)

Glory is the object of God's desire, and the Church is its instrument, that which is bringing it about. Insofar as the Church spreads itself over existence, God is glorifying himself. And "the world must be as nil as possible" in order for the glory of God, thanks to the Church's work, to be as great as possible: the more destitute and contemptible the world is, the more remarkable its reworking (148). Contra Leibniz, for Malebranche "this world is the most abject of worlds. This explains why this world is the most abject world possible, both materially (it is wretched) and spiritually (it is humiliated)" (89).
____

Also very curious of what an "event-less" ontology is, but probably won't have time to dig into it (hence filing it here).

== Link Dump

Another set of links that I want to get into but have to deprioritize.

* Shashank, **"Everything You Ever Wanted To Know About The Stock Market But Were Too Afraid To Ask"**, published 27 Jul 2019. http://shashankr.me/2019/07/27/everything-you-ever-wanted-to-know-about-the-stock-market-but-were-too-afraid-to-ask.html
* **"How to `geth init` and start geth mining with Docker-compose?"**
https://stackoverflow.com/questions/50598243/how-to-geth-init-and-start-geth-mining-with-docker-compose
* **Typescript guide**: https://basarat.gitbooks.io/typescript/content/docs/project/tsconfig.html
* **Math for game programmers**: http://www.mathforgameprogrammers.com


== Glossary

* link:https://en.wikipedia.org/wiki/Mantissa[**Mantissa**]: 
The fractional part of the common (base-10) logarithm;
or the significand, the significant digits of a number in scientific notation or a floating-point number.
Spotted here: https://golang.org/doc/go1.13
