= Reading List for Sep 2019
Zed Tan <zed@shootbird.work>
:toc: auto
:toclevels: 3
:sectlinks:
:sectnums:
:source-highlighter: pygments
:assetdir: /sep2019-assets

== Human things

=== The Missing Body of the Machine

Ben Medlock, "The body is the missing link for truly intelligent machines",
published 21 Aug 2019 on _Sinapticas_.
Available: https://sinapticas.com/2019/08/21/the-body-is-the-missing-link-for-truly-intelligent-machines

[quote]
____
I understand the appeal of this view, because I co-founded SwiftKey,
a predictive-language software company that was bought by Microsoft.
Our goal is to emulate the remarkable processes by which
human beings can understand and manipulate language.
We’ve made some decent progress: I was pretty proud of the
elegant new communication system we built for the physicist
Stephen Hawking between 2012 and 2014. But despite encouraging results,
most of the time I’m reminded that we’re nowhere near achieving human-like AI.
Why? Because the layered model of cognition is wrong.
Most AI researchers are currently missing a central piece of the puzzle: embodiment.
____

* This is a thought that's been put forward constantly by Hubert Dreyfus,
who argued that embodiment is necessary for a human understanding of the world.
* It's also a train of thought that uses as a premise that human intelligence is the de facto goal of machine intelligence.
* Once you remove that premise, you free up the possiblity of machines that are
intelligent by a different metric than humans are intelligent.
* E.g. humans will never be able to compete with a machine within the bounds of a closed and known system
e.g. Go, Dota 2 etc.
* A useful analogue would be how we consider and measure animal intelligence by basically
imposing a set of human standards e.g. a dog is intelligent if it can be trained to accomplish a series of tasks
* It's been shown that animal intelligence exceeds those bounds once we think past
this imposition of human standards, e.g. a dog is intelligent if it displays self-directedness instead of submitting
itself to a human imposed goal, like breaking out of a cage to get to a bag of food on a shelf, rather than knowing
how to roll over and play dead.
* (I also think that animal training is an inherently colonial and unethical impulse, but that's another story altogether)

[quote]
____
This means that when a human approaches a new problem, most of the hard work has already been done.
In ways that we’re only just beginning to understand, our body and brain,
from the cellular level upwards, have already built a model of the world
that we can apply almost instantly to a wide array of challenges.
But for an AI algorithm, the process begins from scratch each time.
There is an active and important line of research, known as ‘inductive transfer’,
focused on using prior machine-learned knowledge to inform new solutions.
However, as things stand, it’s questionable whether this approach will be
able to capture anything like the richness of our own bodily models.
____


=== The Human Log

In a related article or tweet that I cannot remember the source for (will update when I do),
someone described journaling as a "diagnostic socket" for the human brain,
a metaphor that I am quite partial to given how much I'm accused of being
very much like a machine (and how much I prefer interacting with them rather than humans).

In a similar vein,
link:neilkakkar.com[Neil Kakkar]
writes a longer post about how humans also,
like computers and other systems, need a log:
https://neilkakkar.com/the-human-log.html

I enjoy in particular his opening grafs on the nautical origins of the term "log"
(I am quite fond of ships and the sea):

[quote]
____
The log is an interesting invention. It began with 16th century ships – surrounded with water, no land in sight, no sense of direction, and no sense of speed. What did you have to compare your speed with anyway?

The sailors were ingenious. They used a log - a real piece of wood - attached to a string. They’d throw it in the water and use it to measure speed1. Then they’d track this speed over time, in a logbook.

That’s the origin story of log books, now known as logs.

Over time, the logs grew to track even more information. The sailors felt that tracking their speed wasn’t enough. They filled gaps in their measurements - the weather, incidents, and the last time someone cleaned the toilet.

The idea? If you have a log, you can figure out what went wrong. You can figure out where you made mistakes. If the ship crashes, you know the last state it was in, thanks to the logs.
____

Other noteworthy points:

* "[...] logs serve two main purposes. (1) Crash resolution and (2) Behaviour detection."
* "Every important system has logs since they’re necessary to improve the system over time."
* Human logs as  means to detect "micro-crashes", and derive diagnostic value from them.
* Micro-crashes are things like headaches, sleep-irritation i.e. minor ailments that may signal deeper issues.
* Nakkar suggests quite a list of things that should go into a human log …
which forms what I can see is a useful baseline but
seems a bit too mechanical for my own taste
(plus that's a lot of work) e.g. daily weight, _bowel movements_ etc.
* Data-driven journaling.

On a separate note, a todo app that I've been using since 2014 has stopped syncing on iCloud,
so I really need to figure out a better way to sync all my thoughts
the links that I collect on a daily basis. May need to actually build my own.

== Philosophy

=== Desire without lack

https://ndpr.nd.edu/news/malebranche-theological-figure-being-2/

Reviewed by Ed Pluth, California State University, Chico.
Alain Badiou, Malebranche: Theological Figure, Being 2,
Jason E. Smith and Susan Spitzer (trs.), Columbia University Press, 2019, 193pp., ISBN 9780231174787.

Not really interested in Badiou, but I found this snippet particularly interesting:

[quote]
____
Consistent with not having a doctrine of the event, Malebranche also has to puzzle out a way in which God can desire, but still not lack.

> Malebranche's big problem will be how to think desire without lack. Glory, as we shall see, is ultimately a category of God's desire: what God desires is his own glory. This goes without saying, because if he didn't desire it, he wouldn't make anything, and especially not the world. (85)

Glory is the object of God's desire, and the Church is its instrument, that which is bringing it about. Insofar as the Church spreads itself over existence, God is glorifying himself. And "the world must be as nil as possible" in order for the glory of God, thanks to the Church's work, to be as great as possible: the more destitute and contemptible the world is, the more remarkable its reworking (148). Contra Leibniz, for Malebranche "this world is the most abject of worlds. This explains why this world is the most abject world possible, both materially (it is wretched) and spiritually (it is humiliated)" (89).
____

Also very curious of what an "event-less" ontology is, but probably won't have time to dig into it (hence filing it here).

== Link Dump

Another set of links that I want to get into but have to deprioritize.

* Shashank, **"Everything You Ever Wanted To Know About The Stock Market But Were Too Afraid To Ask"**, published 27 Jul 2019. http://shashankr.me/2019/07/27/everything-you-ever-wanted-to-know-about-the-stock-market-but-were-too-afraid-to-ask.html

