= Control (2019)

- House of leaves, the game.
- Ahti the janitor.
- janitorial duties as transcendent, as profound force for good

- very strange game
- 'feels like home'. the most homely game i've ever played.
- feels like I can inhabit the game space really comfortably. not common in games.

- the weird thing is: combat is not particularly good, platforming is sticky and annoying.
- but the game feels good. why?
- atmosphere/mise-en-scene is great
- worldbuilding is great


- Could it be the appeal of dismantling brutalist, rigid corporate structures?
but yet still staying within the bounds of that structure?
but still the heart of it is empty? that it still collapses
back into empty pointless rebellion, that the dismantling
ultimately is pointless, that it gives rise to just
another controlling structure?

futile? the penultimate sequence is pointless/culmination of
futile rebel-fantasy, which is ultimately the underlying message
of the whole game?

think about it. one of the final sequences is being
trapped in a literal office-nightmare serving never
ending cups of coffee and about never-enough productivity etc.
